### ISSUE TITLE
I want to build a DGB pool in china

### ISSUE THREAD

**Issue by AKIo0O** [digibyte/digibyte#1]
But I dont know how to do it.

Please support me.

I'm a DGB fans.Thx.

**Comment by digibyte** [comment]
Have you checked out MPOS? https://github.com/MPOS/php-mpos

**Comment by ghost** [comment]
OR: if you want to set up a P2Pool node, here's how:
http://www.reddit.com/r/Digibyte/comments/1xw61x/p2pool_how_to_make_your_own_personal_p2pool_node/
