### ISSUE TITLE
Repetitive Digibyte core wallet runtime error when trying to sync headers  

### ISSUE THREAD

**Issue by PaulF1** [digibyte/digibyte#100]
This issue tracker is only for technical issues related to digibyte-core.

General digibyte questions and/or support requests and are best directed to the [DigiByte StackExchange](https://digibyte.stackexchange.com).

For reporting security issues, please read instructions at [https://digibytecore.org/en/contact/](https://digibytecore.org/en/contact/).

### Describe the issue
I have been trying to initiate the installation of a 32 bit Digibyte core wallet on my PC but when it reaches around 95% of syncing headers a runtime error occurs (Microsoft Visual C++Runtime Library). Being a bit of a newbie with limited technical knowledge and not fully understanding the system I sent a number of DGB tokens from an exchange to an address that was generated on the wallet that wasn't yet synced. I am afraid that they have been lost forever, however on digiexplorer I can see that the the tokens were successfully received to that address. So firstly it would be appreciated if you can provide assistance to successfully install a wallet and secondly can you confirm that once the wallet is initiated I will be able to retrieve the tokens from the block chain to the address where the tokens have been received (I saved the digiwallet.dat file from that initial wallet setup). 

### Can you reliably reproduce the issue?
Yes I have tried to install the wallet numerous times

#### If so, please list the steps to reproduce below:
1. I open wallet as admin
2. I wait
3. The issue appears (runtime error) when the syncing headers reach over 95%

### Expected behaviour
The wallet should sync 

### Actual behaviour
The wallet Crashes...C++ runtime dialouge box.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of digibyte-core are you using?
6.14.2

### Machine specs:
- OS: 32 bit / x64 based processor
- CPU: Intel (R) Core (TM) i5
- RAM: 4 GB
- Disk size: 230 GB / 42.5 free
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
I have tried the following steps repeatedly:
1. I  don't believe any wallets have been successfully generated, however I have saved the address to where the tokens have been received (according to digiexplorer)
2. I have removed the application.
3. I restarted the computer.
4. I believe I have enough space on HDD for min requirements
5. All other apps and programs are closed when a reinstall has been tried.
6. The problem remains

Any help on being able to sync the wallet and successfully retrieving the tokens will be very much appreciated.

Thank you

**Comment by jdabs** [comment]
Great write up

**Comment by PaulF1** [comment]
Thanks! Hopefully someone will be able to assist, I really don't want to lose my DGB tokens as I think potentially the company has a bright future

**Comment by salmanmarvasti** [comment]
install on 64bit machine. due to not having a professional development team behind digibyte most development has been with community volunteers.. Unfortunately the 32 bit wallet has not been maintained.

**Comment by digicontributer** [comment]
Hi can you try and add the following to your digibyte.conf file and restart digibyte-core

`dbcache=150`
`maxmempool=150`

**Comment by digicontributer** [comment]
This should be fixed in the next release #104

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
