### ISSUE TITLE
Error when trying command make HOST=x86_64-w64-mingw32

### ISSUE THREAD

**Issue by skljoc** [digibyte/digibyte#105]
/bin/sh: 1: Syntax error: "(" unexpected
funcs.mk:242: recipe for target '/mnt/c/digibyte/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-bbb375fcdd9/./.stamp_configured' failed
make: *** [/mnt/c/digibyte/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-bbb375fcdd9/./.stamp_configured] Error 2

**Comment by digibyte** [comment]
Please try latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
