### ISSUE TITLE
digibyte-qt problem

### ISSUE THREAD

**Issue by ghost** [digibyte/digibyte#108]
i have problems

> ~/digibyte/src/qt$ ./digibyte-qt
> QXcbConnection: Could not connect to display
> Aborted

How can i fix this problem ?

**Comment by nicolespin** [comment]
It seems that you open digibyte-qt with non-GUI environment such as remote or ssh connection.

**Comment by digicontributer** [comment]
You probably want to use digibyted and digibyte-cli instead of digibyte-qt.
