### ISSUE TITLE
digibyte.conf rpc port issue

### ISSUE THREAD

**Issue by ghost** [digibyte/digibyte#109]
I want to add Digibyte to my exchange, but i have problem.

I have Bitcoin, Litecoin.

Bitcoin rpc port:8332
Litecoin rpc port:9332

When i use Digibyte rpc port:8332 Bitcoin core doesnt work... How can i solve this problem ?

**Comment by digicontributer** [comment]
Each coin needs to use a different rpcport. By default DigiBytes is 14022.
