### ISSUE TITLE
Links on homepage point to bitpay/insight repo

### ISSUE THREAD

**Issue by gabegattis** [digibyte/digibyte#111]
Hey there. I'm from the BitPay team. I see that you have forked a lot of our bitcore work to build software for digibyte. This is great, but there is one issue.

On your fork of insight, the links on the main page still point to our repository. (see https://digiexplorer.info/) This results in a lot of confused digibyte users opening issues on our repo. There is nothing we can do for them. We would appreciate it if you could update those links.

Sorry I opened this issue on this repo. Github isn't letting me open an issue on your insight fork.

**Comment by jdabs** [comment]
I do see the issue and we're looking into it. Thanks for letting us know.

**Comment by digicontributer** [comment]
Hey sorry about that. Fixed and deployed in https://github.com/digibyte/insight/commit/6402f4acc2a55cb511418fcc6bfde78a687caaa0
