### ISSUE TITLE
Where i am lagging in DIGIBYTE installation since address generated by it not validated 

### ISSUE THREAD

**Issue by lettertoamit** [digibyte/digibyte#122]
I am facing these error in DIGIBYTE with UNOMP  . When i run "node init.js"  
I am working with digibyte with unomp. with qubit alogrithm : 

I am not getting why and how i need to validate address i generated address by ./digibyted itself.Over all i am stuck in UNOMP with digibyte kindly help me here with these errors i encounter either of them.

> [2018-04-06 13:50:53.877] [INFO] [default] - Run Workers [2018-04-06 13:50:53.885] [FATAL] [default] - Payments digibyte Daemon does not own pool address - payment processing can not be done with this daemon, {"isvalid":true,"address":"D7w4wVkSXEEYqY1vmMe2esCewEMinG4wrN","scriptPubKey":"76a9141ea20cfd9b708b94ac68681378550bbc4a966c7e88ac","isscript":false,"iswitness":false}
> 
> 
> [2018-04-06 14:51:16.294] [WARN] [default] - Switching Setup Thread 1 Switching "switch1" listening for qubit on port 3344 into digibyte
[2018-04-06 14:51:16.301] [DEBUG] [default] - Pool digibyte Thread 1 Could not start pool, error with init RPC validateaddress - {"code":-28,"message":"Loading block index..."}
{ code: -28, message: 'Loading block index...' }

**Comment by Jabbalobi** [comment]
Did you find the solution? having the same problem here with UNOMP  as well as Digihash.

**Comment by lettertoamit** [comment]
yes , We run that properly and successfully.

**Comment by ghostycc** [comment]
WHat about a solution then ? :)

**Comment by lettertoamit** [comment]
I first assured that digibyte is running properly. Worked on UNOMP config files .  the more important is you need to set correct config file correct ports , algorithm also you should have qubit.conf for stratum.

**Comment by elmondyong** [comment]
a bit unclear on your last statement. i already have digibyte.conf in /root/.digibyte, where this qubit.conf path location?

**Comment by lettertoamit** [comment]
qubit.conf is inside stratum/config folder

**Comment by elmondyong** [comment]
i already have the config.json under unomp folder, where is the mention path?

i'm also no clue at all on the content of the file, can you show it as example (if no cinfidential stuff)

**Comment by chistaesse** [comment]
The payment UNOMP library use `validateaddress` RPC command whish is deprecated with 6.16.x wallet version. The `ismine` result is not anymore returned. You have to change this RPC call to `getaddressinfo`. But be carefull, if you use UNOMP with other coins, `getaddressinfo` is not a standard or common command!

**Comment by ChillingSilence** [comment]
More info on the RPC changes here: https://medium.com/@josiah_digibyte/technical-new-address-formats-and-rpc-calls-c1119317a76c
