### ISSUE TITLE
Digibyte is consuming high amount of memory causing process to shut down

### ISSUE THREAD

**Issue by lettertoamit** [digibyte/digibyte#123]
./digibyted process is consuming high amount of memoy around 8 gb. and forcing server to shut down . Can any one there to help me with this issue.

**Comment by arunsatyarth** [comment]
I have the same issue. My server is 2 GB. But it gives out of memory error just after progressing to 4% sync. I have no other process running.

**Comment by ChillingSilence** [comment]
Going to try and get this looked into under #144 , closing this and handling all under one git issue
