### ISSUE TITLE
ubuntu repository ppa digibyte team does not exist

### ISSUE THREAD

**Issue by sant0004** [digibyte/digibyte#124]
In ubuntu server i unable to compile due to repository  pps file does not exist in launchpad page not found below link https://launchpad.net/~digibyte/+archive/digibyte

kindly help to resolve the error

**Comment by alidtoran** [comment]
I have the same problem on ubuntu 16.04

**Comment by ChillingSilence** [comment]
Use ppa:bitcoin/bitcoin as per notes from #164 , build notes will be updated shortly.
