### ISSUE TITLE
No networkhashps in json-answer on getmininginfo method

### ISSUE THREAD

**Issue by cornac** [digibyte/digibyte#125]
![2018-05-02 12 02 35](https://user-images.githubusercontent.com/36678821/39514734-c1ffa5e2-4e00-11e8-96f6-18186bb619b0.png)

I expect obtain networkhashps for selected algo.
![2018-05-02 12 03 30](https://user-images.githubusercontent.com/36678821/39514844-05e9ccb0-4e01-11e8-96dd-85e5333bc46f.png)

**Comment by cornac** [comment]
How can I get nethashrate for one algo only?

**Comment by belmix** [comment]
?
