### ISSUE TITLE
Digibyte 6.14.2 version cannn't send money to 6.16.2 version's multsigaddress 

### ISSUE THREAD

**Issue by skawhdgjs** [digibyte/digibyte#127]
when i transferred money to 6.16.2's multisigaddress( start with 'S' rather than '3') , I got the error that
`invalid address`

6.14.2 version core take transaction to address start with 'S'

sender : 6.14.2
Receiver :  6.16.2

window's 10

may be need some address converter like bitcoin-cash's address problem solution
https://cashaddr.bitcoincash.org/

**Comment by ChillingSilence** [comment]
This is correct.
6.14.2 is unaware of how to send to Bech32 or the newer format SegWit addresses. Support was added in 6.16.2 for the new formats. Upgrading to the new wallet will resolve your issue.
