### ISSUE TITLE
I am gettting this issue when i started my node init.s Pool digibyte Thread 1 Could not start pool, error with init RPC getinfo - {"code":-32601,"message":"getinfo\n\nThis call was removed in version 6.16.0. Use the appropriate fields from:\n- getblockchaininfo: blocks, difficulty, chain\n- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings\n- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion\n\ndigibyte-cli has the option -getinfo to collect and format these in the old format."}

### ISSUE THREAD

**Issue by Rockeronhunt** [digibyte/digibyte#129]

**Comment by cornac** [comment]
Just update your NOMP.

**Comment by Rockeronhunt** [comment]
thanks cornac u mean https://github.com/UNOMP/unified-node-open-mining-portal dis one???
I am already using updated NOMP

**Comment by cornac** [comment]
I use zone117x NOMP. 
https://github.com/zone117x/node-open-mining-portal

https://cryptopool.gq/ggb
https://cryptopool.gq/dgbs
And it’s working fine

**Comment by Rockeronhunt** [comment]
ok thankx @cornac  i will do with dis if i find any problem i ll let u know thanks :)

**Comment by Rockeronhunt** [comment]
I try  using z-nomp with bitcoinprivate & everything is successfully working but when i mined my coin i am not getting any block. 

![image](https://user-images.githubusercontent.com/32458821/41307776-b7f40ef0-6e97-11e8-98db-9d033b4da40e.png)


please help me in dis

**Comment by cornac** [comment]
May be you need more hashpower?))))
On my DGB pool 100+ Asics S9 and 150+ ASICS L3+  and we are finding about 20-30 blocks per day on each algorithm

And on screenshot you have no any workers. Are you sure that you have right config your miner?!

**Comment by Rockeronhunt** [comment]
**100+ Asics S9 and 150+ ASICS L3+**  
where this thing have to write in the code ??

in the screen shot i get the screenshot after completing the mining
@cornac  please reply

**Comment by cornac** [comment]
Nowhere. I work with people who say in my support channel how many asics they connected. And I see hasrate of pool. 
If each asic use original worker’s name then on dashboard show how many workers on my pool. 

P.s. I use php-mpos with NOMP.
