### ISSUE TITLE
"getdifficulty" call displays other diff than the pow algo set in conf file.

### ISSUE THREAD

**Issue by Widi92** [digibyte/digibyte#131]
http://prntscr.com/jlridu
On the screenshot you can see that the pow _algo is set as scrypt, but when I try the "getdifficulty" call it displays the groestl difficulty and not the scrypt.

How can I fix this issue?
Wallet is up to date compiled on ubuntu 16.04

**Comment by cornac** [comment]
Try getnininginfo.  all difficulties trhere

"blocks": 6716958,
  "currentblockweight": 4000,
  "pow_algo_id": 0,
  "pow_algo": "sha256d",
  "difficulty": 911811313.9334098,
  "difficulty_sha256d": 911811313.9334098,
  "difficulty_scrypt": 65182.90726969191,
  "difficulty_groestl": 376541.2666708904,
  "difficulty_skein": 388553.0740752782,
  "difficulty_qubit": 617608.381403469,
  "errors": "",
  "pooledtx": 0,
  "chain": "main",
  "warnings": ""

**Comment by Widi92** [comment]
Mpos uses the getdifficulty call. I changed the source code and recompiled to get the right diff for mpos statistics.

**Comment by cornac** [comment]
@Widi92, it’s in bitcoinwrapper.php. Just change method to getmininginfo

**Comment by ChillingSilence** [comment]
As of 6.16.4 , all algo difficulties are displayed in getblockchaininfo, as there are a number of calls deprecated in upstream Bitcoin Core so we have merged to keep in-line with those changes.
