### ISSUE TITLE
UNOMP - How to getnewaddress and dumprivkey commands

### ISSUE THREAD

**Issue by jaredthesovereign** [digibyte/digibyte#132]
Hi,  I'm trying to test out a digibyte pool using UNOMP.  I installed the core wallet correctly and my issue is that I am not able to find a -getnewaddress or -dumpprivkey cmds in the digibyted or digibyte-cli so that I can configure the json correctly.  

How do I get these?

**Comment by cornac** [comment]
digibyte-cli help |grep 'getnewaddress\|dumpprivkey'
In digibyted deleted cli commands. Use cli without “-“. Like this “digibyte-cli getnewaddress”

**Comment by jaredthesovereign** [comment]
got it.  thx cornoc

**Comment by jaredthesovereign** [comment]
Cornoc - After getnewaddres and dumpprivkey and inputting the new address into the digibyte.json file I'm getting the following response now.  (I've done it twice now.) Thoughts?

 Payments digibyte Daemon does not own pool address - payment processing can not be done with this daemon, {"isvalid":true,"address":"[REDACTED]","scriptPubKey":"[REDACTED]","isscript":false,"iswitness":false}

Also, when I do a getwalletinfo the following is returned:

{
  "walletname": "",
  "walletversion": 159900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1527911537,
  "keypoolsize": 999,
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00100000,
  "hdmasterkeyid": "[REDACTED]"
}

**Comment by cornac** [comment]
Address is in wallet?
