### ISSUE TITLE
test_digibyte many failures on Linux x64 build

### ISSUE THREAD

**Issue by Heraisu** [digibyte/digibyte#138]
### Expected
A released build would pass all of its own tests...

### Actual
test_digibyte fails many tests.

### Reproduction Steps

1. Download linux x64 wallet link from website.
2. tar
3. go to /bin
4. ./test_digibyte > test_digibyte.out.txt (attached below)

### Version
6.16.2  Linux x64
Website link:  https://github.com/digibyte/digibyte/releases/download/v6.16.2/digibyte-6.16.2-x86_64-linux-gnu.tar.gz

### OS
Ubuntu 16.04
### Test output 

[test_digibyte.out.txt](https://github.com/digibyte/digibyte/files/2153385/test_digibyte.out.txt)

**Comment by Heraisu** [comment]
Tried building from source on the same system. Current master branch fails the tests in the same spectacular fashion.

**Comment by Heraisu** [comment]
Dead project... got it

**Comment by ChillingSilence** [comment]
Duplicate of #133
