### ISSUE TITLE
digibyte go wallet not completing trans action

### ISSUE THREAD

**Issue by rmdsys** [digibyte/digibyte#139]
transaction wont show up in digibyte go wallet chrome app

**Comment by rmdsys** [comment]
i tried to lookup transaction and wallet address but not such transaction is there  even though my nano says 11943 conformations 
can anyone help with this ?

**Comment by ChillingSilence** [comment]
DigiExplorer.info (Which DigiByte Go uses) was under maintenance at the time. It should show up now.
