### ISSUE TITLE
Consistent High RAM Usage

### ISSUE THREAD

**Issue by diveyez** [digibyte/digibyte#140]
After trying on several different ARCH's and Distro's
I have been unable to utilize the -qt for linux64 without having a huge 20-40% RAM hit.
Is there a setting to limit this in the config file for this particular wallet?

**Comment by diveyez** [comment]
Nothing? Nobody has anything to say?

**Comment by ChillingSilence** [comment]
Going to try and get this looked into under #144 , closing this and handling all under one git issue
