### ISSUE TITLE
Block submission failed due to "high-hash"

### ISSUE THREAD

**Issue by sam-semillia** [digibyte/digibyte#141]
Hi,

since the update to version "DigiByte Core v6.16.2 Official Release" I have the following issue: I always get a block submission rejection due to "high-hash". This issue was not with the version 6.16.1. 

Is that behaviour correct in the new version?

Thanks, br

**Comment by ChillingSilence** [comment]
Have been unable to reproduce this anywhere else.
If this issue persists, please test with 6.17.2 and provide some more information, such as:
- Algo
- Mining pool software (if applicable)
- OS details
- Any other information such as relevant logfiles.
