### ISSUE TITLE
Not create new adress (win - v6.16.4  Desktop Wallet)

### ISSUE THREAD

**Issue by Z-IDDQD** [digibyte/digibyte#147]
Not create new adress (win - v6.16.4  Desktop Wallet)
there is no button in the window

**Comment by Z-IDDQD** [comment]
PS only possible through the debug window*

**Comment by ChillingSilence** [comment]
This was intentional, see upstream Bitcoin Core changelog for 0.16: https://bitcoin.org/en/release/v0.16.0#gui-changes
