### ISSUE TITLE
ERROR: AcceptBlockHeader - block invalid

### ISSUE THREAD

**Issue by roccomuso** [digibyte/digibyte#149]
Having a bunch of errors after only 42MB of downloaded chain (using the latests 6.16.5 release):

```
2018-09-21T14:10:25Z ERROR: AcceptBlockHeader: block 007ce97997cda6be9fe22a9573e09efd0bda1dc8983134b2ff329a1239099d0b is marked invalid
...
```
I'm not having this error with the oldest (6.16.3 release).

**Comment by digibyte** [comment]
Issue fixed, please pull from master:

https://github.com/digibyte/digibyte/commit/a237b1699631bf0aebcb565bb815047b56994e65

**Comment by roccomuso** [comment]
I can pull from master, but this is affecting the tagged release v6.16.5, that is broken. Please fix that or release a new patched one.
