### ISSUE TITLE
Pool Setup

### ISSUE THREAD

**Issue by vr4dude316** [digibyte/digibyte#152]
Hello.  Just setup a DGB pool.  66.187.187.73:8080

Can someone try this pool once the blockchain finishes download?

Thanks

**Comment by ChillingSilence** [comment]
Your best bet is to join the Mining Channel on Telegram and have a chat with the people there, somebody is more likely to be able to point a miner at a pool there depending on the algo. Links at the bottom of digibyte.io :)
