### ISSUE TITLE
Digibyte error getblocktemplate result

### ISSUE THREAD

**Issue by PanelTrader** [digibyte/digibyte#153]
04:15:13: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:15:13: Digibyte error getblocktemplate result
Digibyte error getblocktemplate result04:15:34: connecting to coind DGB
04:15:34: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:15:34: ERROR getaccountaddress Digibyte
04:15:34: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:15:34: Digibyte error getblocktemplate result
04:15:55: connecting to coind DGB
04:15:55: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:15:55: ERROR getaccountaddress Digibyte
04:15:55: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:15:55: Digibyte error getblocktemplate result
04:16:16: connecting to coind DGB
04:16:16: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:16:16: ERROR getaccountaddress Digibyte
04:16:16: ERROR: rpc_do_call: 127.0.0.1:14022 500
04:16:16: Digibyte error getblocktemplate result

What is the my problem in yiimp ???

**Comment by ChillingSilence** [comment]
You need to update it to support the new RPC calls pulled from Bitcoin Core 0.17:
https://medium.com/@josiah_digibyte/technical-new-address-formats-and-rpc-calls-c1119317a76c
