### ISSUE TITLE
CheckForkWarningConditions: Warning: Large valid fork found   forking the chain at height 

### ISSUE THREAD

**Issue by digibyte** [digibyte/digibyte#16]
Issue not resolved:
Could be because warning is sensing blocks on different algos. 

Warning example: 
`CheckForkWarningConditions: Warning: Large valid fork found
  forking the chain at height 187700 (9f6367167324f5120afcd47bfe5d38e059530991a7aa344f674a04ceba624983)
  lasting to height 187701 (f6b7f69f78eab769253e565a9bde9a28df8af23790eff987c6f923dff4b0be44).` 

Likely Place to start looking for fix:https://github.com/digibyte/DigiByteProject/blob/master/src/main.cpp#L1491

https://github.com/digibyte/DigiByteProject/blob/master/src/main.cpp#L1517

**Comment by l0rdicon** [comment]
just to confirm, a  -reindex was attempted ?  

First thing to try in a case like this is to -reindex as it can be caused by corruption

Looking into this one deeper

**Comment by l0rdicon** [comment]
I'm stealing this from stackexchange but here it is explained. 

A signature check failed for a valid transaction. This likely indicates a CPU or RAM problem with the system you're running on (even though you don't see regular errors in normal operation, Bitcoin does so many computations during validation that it's likely to see them more).

The result of this is that bitcoind marked the chain this transaction was in as invalid, and rejects new blocks in it.

To rebuild your database, you can start the client with the -reindex flag (if you exit while rebuilding, it will pick up where it was stopped on the next run).

One workaround that helps in some cases is running with -par=1, making validation only run in one thread. This seems to reduce the load enough to make some CPUs not cause errors anymore.

**Comment by l0rdicon** [comment]
also you can try adding these lines to your digibyte.conf

checkblocks=10
checklevel=1

**Comment by digibyte** [comment]
Fixed with https://github.com/digibyte/DigiByteProject/commit/9f8d53d1abc7795204932534e7c6d99211f5ee6a
