### ISSUE TITLE
DGB Core problem

### ISSUE THREAD

**Issue by LAZARUS4829** [digibyte/digibyte#160]
I have Windows 64-Bit v6.14.2 wallet.  My send button no longer responds.  No pop-up window for passphrase comes up.  It used to work.

**Comment by ChillingSilence** [comment]
Please upgrade to 6.16.5.1 to ensure you are able to send to all address-types. We now support new dgb1 for bech32 and S for SegWit address formats.

**Comment by LAZARUS4829** [comment]
I now have 6.16.5.  Is it the very same as 6.16.5.1?

**Comment by ChillingSilence** [comment]
6.16.5.1 contains an additional fix for fresh synchronizations of the blockchain, though shows 6.16.5 in the "About" section of the application.
