### ISSUE TITLE
Raspberry Pi 3 Terminating After 2/3Hours of running

### ISSUE THREAD

**Issue by br3nn** [digibyte/digibyte#165]
Hi, 

So i have spent the last couple of days trying to get the Arm release (Latest) running on my raspberry pi 3. 

It seems after 2hours of syncing without warning the application will terminate with an out of memory error displayed. 

*OS Raspbian Latest
Swapfile 4Gb (Also tried 10gb), on the SD card and on a external USB Pen Drive
(Same 2hour window)

Running Digibyted on the raspbian Desktop, 
Again same 2hour window

The longest sync time i have had is 3hours, which was headless, no VNC server installed to gain more available ram.

*I have also set up a watch every 60 seconds to sync memory to disc which again 2hour window.

I can confirm when the program terminates the swap file is no where near full maybe using 1.1gb, and the active memory (RAM) around the 880/900mb mark still space available. The client doesn't move from 8 connections when running digibyte-cli -getinfo blocks go up nicely i think i hit 137k height on my 3hour window. 

I would love to put my Pi3 to good use (Granted i'm aware it could take ages for for first sync so happy to part download a blockchain if that helps or even get mine up to scratch and clone then host my image for others to join)

**Comment by ChillingSilence** [comment]
This is being addressed under issue #144
