### ISSUE TITLE
[Feature] Add Anonymous Transactions

### ISSUE THREAD

**Issue by asddsaz** [digibyte/digibyte#166]
**Description**: General discussion on adding opt-in anonymous transactions to DigiByte
**Similar Reddit Post**: https://www.reddit.com/r/Digibyte/comments/94mcs1/any_plans_for_privacy_features/

- [ ] Add Anonymous/Shielded Transactions
_________
Want to back this issue? Post a [bounty on it](https://www.bountysource.com/issues/67416016-feature-add-anonymous-transactions)! We accept bounties via [Bountysource](https://www.bountysource.com/).

**Comment by ChillingSilence** [comment]
In the wise words of Riccardo "Fluffypony" Spagni, anonymity isn't something you "achieve", it's a constant cat & mouse battle, and so any undertaking like this would need long-term involvement and commitment from developers. It's not something currently planned.

**Comment by ChillingSilence** [comment]
No interest on bountysource either. As this would require some major code commits and likely long-term developer commitment to it, this issue is being closed for now.
