### ISSUE TITLE
WalletNotify failing when trying to run bash command.

### ISSUE THREAD

**Issue by AskDavis** [digibyte/digibyte#169]
Hello, I have your DigiByte core running on ubuntu unix without QT. I have added new addresses as a watch only using importaddress. When the money gets in the wallet from that address it runs a command i have here walletnotify=/Coin/Digibyte/transaction.sh %1. it errors everytime even when i try curl here in digibyte.conf.
 walletnotify=/usr/bin/curl -d "txid=$1" -d "secondRun=false" -d "key=example" "https://example.com/api/transaction/"

Error the same regardless of how i call it.
 runCommand error: system(/Coin/Digibyte/transaction.sh df772f3934565edfcb01a82df6e47c055ec8901ac95fd352eed663f9fe401d7e) returned -1.

I have tried over and over again with different ways, curling in the walletnotify, runing the sh file. still same error. not sure why but it wont let me run anything for wallet notify.

digibyte.conf:
rpcuser=
rpcpassword=
server=1
listen=1
txindex=1
walletnotify=/Coin/Digibyte/transaction.sh %s

transaction.sh
#!/bin/bash
/usr/bin/curl -d "txid=$1" -d "secondRun=false" -d "key=example" "https://example.com/api/transaction/"

/bin/sleep 1800

/usr/bin/curl -d "txid=$1" -d "secondRun=true" -d "key=example" "https://example.com/api/transaction/"

anyway you can help will be appreciative!
thanks
Jacob

**Comment by ChillingSilence** [comment]
Does it do it if you just do the curl command once, without the sleep etc?

**Comment by AskDavis** [comment]
yes i've tried just one command for curl and still same issue. have you ran into this issue at all?
Thanks 
Jacob Davis

**Comment by ChillingSilence** [comment]
Checking through the Bitcoin docs, it looks like it's supposed to be %s, not %1 like it would be in bash.

Edit: So I believe you'd set:
walletnotify=/Coin/Digibyte/transaction.sh %s
curl should then take the %s as $1

**Comment by AskDavis** [comment]
Yes I’m sorry, I typed that wrong, ill double check when I get home, but yes I’m my testing it’s %s. It shows in the debug.log file the error as stated above with the correct transaction. It’s just when running any command. Thanks again for your help.

**Comment by AskDavis** [comment]
okay, i have continued to run into this issue. I have tried on Debian, Centos and Ubuntu with the exact same results. Error: runCommand error: system(/Coin/Digibyte/transaction.sh 90530de5b11d5627818e5208881e2115e93a8c74b535d36f3b328784e61bd2fc) returned -1
it wont run any bash commands. 
thanks.
Jacob

**Comment by AskDavis** [comment]
here are my build steps through ubuntu server 16.04. 
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8842ce5e && \
  echo "deb http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial main" > /etc/apt/sources.list.d/bitcoin.list

apt-get update
  apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
apt-get upgrade
mkdir /Digibyte
mkdir /Coin
cd /Coin
mkdir /Digibyte
cd
git clone https://github.com/digibyte/digibyte.git /Digibyte
cd /Digibyte
./contrib/install_db4.sh `pwd`
export BDB_PREFIX='/root/digibyte/db4'
./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make
make install

cp /Digibyte/digibyte/src/digibyted /usr/local/bin/
cp /Digibyte/digibyte/src/digibyte-cli /usr/local/bin/

then i run
digibyted -datadir=/Coin/Digibyte -printtoconsole.

here is my digibyte.conf
server=1
listen=1
txindex=1
walletnotify=echo %s

can reproduce the error ive been getting?
runCommand error: system(echo 90530de5b11d5627818e5208881e2115e93a8c74b535d36f3b328784e61bd2fc) returned -1

again i've ran this on debian, ubuntu, and centOS with the same error.
Thanks for your help

**Comment by calvinweight** [comment]
If anyone has any suggestions we would love your help. This is still an open issue. We have an interim solution, but would like to get this working if at all possible. Thank you!

**Comment by digibyte** [comment]
Have you been able to resolve this yet? We want to help make sure we get this resolved and documented for people in the future.

**Comment by calvinweight** [comment]
No not yet. We have a temp solution in place but would really like to figure out this issue for the long term.

**Comment by calvinweight** [comment]
Bump - trying to keep this live since we would love to get this solved. If possible, have a developer reach out to me personally.

**Comment by digibyte** [comment]
Are you by any chance getting this error somewhere "No rpcpassword set - using random cookie authentication" or something similar in your log file about a cookie not being set?

rpcuser, rpcpassword will be deprecated in favor of setting a cookie for authentication in latest versions of DGB & BTC, however they should still work..
https://bitcoin.stackexchange.com/questions/46782/rpc-cookie-authentication

**Comment by ChillingSilence** [comment]
Hi Team,
Even without RPC, you shouldn't need that. This is my test results:
```
master@compiler:~/digibyte$ cat ~/.digibyte/digibyte.conf
server=1
daemon=1
walletnotify=echo %s >> /tmp/tx
```

I then see this in the ~/digibyte/debug.log:
```
2019-03-24T22:48:50Z [default wallet] AddToWallet 89e1d9ae5a2bea49799721ef044806b543a287dfa88fdcdc0679c96b69267fd3  new
2019-03-24T22:48:50Z [default wallet] AddToWallet 89e1d9ae5a2bea49799721ef044806b543a287dfa88fdcdc0679c96b69267fd3  

```

And I can confirm it shows up correctly in the file:
```
master@compiler:~/Downloads$ tail -f /tmp/tx
89e1d9ae5a2bea49799721ef044806b543a287dfa88fdcdc0679c96b69267fd3
89e1d9ae5a2bea49799721ef044806b543a287dfa88fdcdc0679c96b69267fd3
```

Everything is working as expected for me here.

If you do, as I do, do you then get the output of the txid to /tmp/tx ?

Edit: This was run on Ubuntu 18.04
I wonder if there's perhaps something in Centos preventing it? SELinux?

**Comment by AskDavis** [comment]
I will test it and see, anytime I ran echo it gave me the returned  error 1, but I can give it a try again to make sure. Have you by chance tried to run a bash command after and see if that errors on your side? 
Thanks 
Jacob

**Comment by SmartArray** [comment]
Please be sure that your machine does not run out of memory.
Please also check if the bash script has set the correct permissions.

**Comment by AskDavis** [comment]
Hello! Sorry its taken a while to close this issue, but it was a memory issue. Increasing my server to 8gb RAM solved my issue thank you!
