### ISSUE TITLE
Optional Auto Update

### ISSUE THREAD

**Issue by mctrivia** [digibyte/digibyte#174]
Would be nice if there was an optional auto update setting.  Could check versions of connected nodes and if newer then itself is detected checks GitHub for a new release.

Some may chose not to update but headless nodes with no funds in them would have no reason not to update and would help keep network up to date.

**Comment by marpme** [comment]
Well auto-updater would make the consensus changes (hard-forks) automatically applicable — as everyone will always use the same version

But yes there could be something like that, but way more optional

**Comment by mctrivia** [comment]
only if the miners turn auto update on and i doubt they would.

**Comment by ChillingSilence** [comment]
If it's not on by default, end-users likely won't turn it on either unfortunately.

**Comment by marpme** [comment]
also there are a lot of security involved in such automatic updates. Let’s imagine a case where you incidentally introduce a hard fork and most people are auto-updating to it. 

Imagine what bad effects this could happen etc. ... (also MITM attack scenarios)

**Comment by TwoFace12345** [comment]
An auto update is not really fitting a consensus network and also could be dangerous for the stability of the network when an issue is introduced in a new version. A possible other way to help to help keep network up to date (original reason) is to only make a notification in the wallet that a new version is available, based on the connected nodes. And urge the user to investigate this update and install.
