### ISSUE TITLE
Almost 3GB ram used in prune mode

### ISSUE THREAD

**Issue by skironDotNet** [digibyte/digibyte#175]
running DGB in blockchian prune mode -prune flag and I see 34% mem use in 8GB VPS, this is too much

not sure if prune mode matters, may be a duplicate of https://github.com/digibyte/digibyte/issues/144

**Comment by ChillingSilence** [comment]
Confirmed duplicate of #144 , it's the fact we have *so* many blocks right now that's causing this.
34% is 2.7GB which is to be expected. Please follow the progress on #144
