### ISSUE TITLE
Bitcoin copyright notice

### ISSUE THREAD

**Issue by joaocarlosleme** [digibyte/digibyte#176]
commit e97f9575d305be3bae99eb731045ebf411582f49 on 15 Feb 2018 by DigiByte Team wrongly replaced Bitcoin copyright notice by DigiByte. On the commit they actually performed a FIND and REPLACE on everything Bitcoin by Digibyte, including the copyright notice, which is ilegal.

Please adjust. Has been wrong for quite some time.

See the link below for more info in the commit:
https://github.com/digibyte/digibyte/commit/e97f9575d305be3bae99eb731045ebf411582f49#diff-7116ef0705885343c9e1b2171a06be0e

**Comment by ChillingSilence** [comment]
It is my understanding that the MIT license only requires maintenance of the license itself, not attribution.

**Comment by imylomylo** [comment]
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Is part of MIT fyi

**Comment by joaocarlosleme** [comment]
> It is my understanding that the MIT license only requires maintenance of the license itself, not attribution.

Your understanding is wrong. Please reopen until it get fixed.

https://opensource.stackexchange.com/questions/5120/what-if-somebody-removed-my-name-from-mit-license?newreg=3ba7be11e61e4071942f2f303ec9a021
