### ISSUE TITLE
ERROR: CheckInputs() : Maturity v2: tried to spend coinbase at depth 

### ISSUE THREAD

**Issue by digibyte** [digibyte/digibyte#18]
Issue:
Pools are having trouble paying out blocks before maturity reaches 100. This is causing a problem with NOMP as well.
'''2014-09-13 06:53:54 ERROR: AcceptBlock() : rejected nVersion=1 block
2014-09-13 06:53:54 ERROR: ProcessBlock() : AcceptBlock FAILED'''

Relevant code: 
https://github.com/digibyte/DigiByteProject/blob/master/src/main.cpp#L2576

**Comment by l0rdicon** [comment]
I'm reasonable sure the maturity problem was related to  https://github.com/digibyte/DigiByteProject/issues/17    and should be fixed with those updates. also, pools should no longer be able to pay out before maturity is 100. It was increased during the multialgo update to accommodate the multialgos and remain secure.

The increase in block time (as its total maturity, not per algo) should make the wait reasonable short anyways.

**Comment by l0rdicon** [comment]
2nd issue is something else and is quite confusing to me. 

The block was updated to version 2 during the multialgo switch, the reason that version 1 blocks are failing now is that the super majority has been reached, aka more then 95% of the network's blocks are now version 2.  

I'm not quite sure how there block version would be set to version one inless its something specific to the pool. 

My other guess, which I'm currently exploring is that the getblocktemplate rpc function is returning the wrong block version. I will know shortly and will post an update

**Comment by l0rdicon** [comment]
you can see here   https://github.com/digibyte/DigiByteProject/blob/master/src/miner.cpp#L116    that the block is being set to BLOCK_VERSION_DEFAULT  which is initilized here    https://github.com/digibyte/DigiByteProject/blob/master/src/core.h#L30         If there not creating the blocks themselfs then this is old clients trying to push old blocks onto the network, and the network behaving as expected.  If they made this themselfs and it failed to be accepted...  then the problem lays in the pool software I suspect

**Comment by digibyte** [comment]
Fixed with 3.0.2
