### ISSUE TITLE
Password Manager, add digi-ID to an open source password manager

### ISSUE THREAD

**Issue by tristanmarvin** [digibyte/digibyte#183]
The cryptocurrency community needs a fast, secure reliable password manager.  Digi-ID as "masterpassword" linked to an opensource password manager, or code a new password manager hosting the account details on the blockchain.

**Comment by ChillingSilence** [comment]
This is something that would not be handled by DigiByte Core, but should be raised on somewhere with Lastpass, Keepass etc directly.
Alternatively look in to the Digi-ID / AntumID app for Android.
