### ISSUE TITLE
Freemarket Based Supply

### ISSUE THREAD

**Issue by chitranjanbaghi** [digibyte/digibyte#195]
**Money Creation On Free Market and Balanced Demand and Supply**

Stupidity of inflation

We all are familiar with the stupidity of allowing centeral banks to print the money. And problems with fiat.

The inflation that ruins savings and centeral bank’s fear of a deflationary money supply.

But with bitcoin and other crypto we have decided to become centeral bankers who have decided move to the other extreme.

The Money supply is meant not to inflate or deflate. It needs to be set just right any inflation and deflation ruins the price signal system which makes markets inefficient.

**Solution**

Most things have been solved by the crypto because the creation is on the free market and no centeral authroeity is there but the limiting aspect is the Hard limit of total supply.

So should we just inflate the supply at constant rate? No
So should we vote among ourselves how much the supply should be? NO

How can we just know that the supply provided is the supply needed?

Energy and resources

The energy and resources are used for many things and for mining hardware the same resources are needed.

so if using of energy and resources thourgh mining hardwaare create supply of a coin then it is competing with other uses of the same resources.

So if the supply is small and coin starts to deflate the resources and energy that will be dedicated into it will increase. because every one will try to get a big chunk of the higly demanded coin.

Which shows that uses of coin are many and supply is low to account for all the uses.

This will stop when right supply is injected back into the economy to compensate for the increase growth and abundance of products.

How to then set supply formula such that we know economy needs more coins?

The solution I think is of tracking difficulty. 

Let All time high difficulty = supply of coin

This means if difficulty has reached 1 billion there will be 1 billion coin added to the supply to be distributed, the rate at which this supply get distributed can be decided.

So what if now difficulty decrease should be burn coins? NO NO

The supply remains there, for any new supply to come the previous high of the Difficulty has to be breached. and by how much it will be breached that amount gets added to the supply.

Every Break of previous difficulty will only happen when the economy has grown and there is demand for the coin to expand to account for the new products.

Problem with DGB and other hard limit coins?

The supply of DGB is big for current times it like shoving coins in a market which is not demanding it. hence we see so much manipulation because big whales hold big supplies and can move markets.

with the proposed system above the supply will always represent the need of the ecosystem rather then what we believe it should be.

**Why decimal places won’t be the solution.**

World commercial real estate money is about $215 trillion, lets see if we take 21 billion supply and divide 215 trillion we get $10,238 dgb now your suggestion will come that we will transact in decimal places. Which is hard for averarge humans.

But this is just real estate imagine the IOT devices, dapps and smart contracts and other financial intruments that will come to DGB.

the supply won't be able to even account for those things. Now why do we care we will just add another decimal place to it.

Again if you increase decimal place or allow the total supply to adjust same goal is achieved.

with decimal place there is a problem because then some will demand increase of 2 decimal and other will demand 1 decimal place and again rather than letting the market decide few developers will decide. and this can fork the coin.

**What is money?**
The Money is the medium with which goods are exchanged not for which goods are exchanged.

It is the like the oil of the engine and no developers or centeral banker should decide how much oil is needed by the economic engine only engine should itself decided how much it is willing to accept.

**Comment by digicontributer** [comment]
Not the relevant place for this discussion to take place.
