### ISSUE TITLE
Upgraded from an old wallet, new wallet is painfully slow

### ISSUE THREAD

**Issue by bathrobehero** [digibyte/digibyte#197]
So I've upgraded to the new wallet from a some very old ones on multiple computers and the latest wallet on a PC with a 4770k CPU is still loading after 8 hours and 25 minutes trying to open the old wallet, pegging one CPU thread completely. So not even the UI is available yet.

The debug.log is useless, as there are no new lines since over 8 hours ago, latest lines:

init message: Loading block index...
Opening LevelDB in C:\Users\...\AppData\Roaming\DigiByte\blocks\index
Opened LevelDB successfully
 Using obfuscation key for C:\Users\...\AppData\Roaming\DigiByte\blocks\index: 0000000000000000

Also, on another machine where it loaded in over half a day, the debug.log grew to 2.8 gigabytes(!) with messages like this:

UpdateTip: new best=************ height=******* version=*********** algo=* (odo) log2_work=**.*** tx=***** date='*************' progress=********* cache=62.2MiB(36757txo)
* block height for reward is *******

Also, since the new wallet was upgraded to a newer Bitcoin base, it no longer supports solomining with the old miners (Method not found). Make sense for Bitcoin, but not for altcoins.

**Comment by ChillingSilence** [comment]
Easiest / fastest solution is clearing the blocks / indexes directories and re-launching. You didn't upgrade pre-Odocrypt so ended up getting blocks on the orphaned chain, which is what's causing the delays.

Also, you can adjust your logging levels if you don't want the debug.log info by setting:
`-debuglogfile=0`

`getwork` was replaced with `getblocktemplate` several years ago now. There is solo-mining functionality for Odocrypt available here: https://github.com/digibyte-core/odo-miner

**Comment by bathrobehero** [comment]
A new (empty) wallet opens and syncs in about 1 hour, so it's beyond dumb that it can't be done with a used wallet, becasue syncing a new wallet from scratch then reopening it with an old wallet doesn't take any extra time at all!

And sure, getwork was replaced, and again, it makes sense for BTC - which nobody solomines anymore - but not for altcoins! And yes, getwork was removed several years ago, roughly around the time altcoin devs started to mindlessly copy paste newer repositories without understanding the changes. Fewer mining options mean less decentralization. And most algos are very well optimized by now and not being updated for years now, so no getworktemplate, so you can't really solomine them. /rant

**Comment by ChillingSilence** [comment]
Re-syncing takes less time if you're not using txindex. If you are, it'll take longer, obviously.

With DGB mining, in the last 12 hours I'm counting 87 different miners (Edit: Unique coinbase addresses)
With BTC or LTC, I count < 25 in the last 2+ days each.

That doesn't even include the likes of me, solo mining with Odocrypt, my last block found with 3x DE10-Nano's was 2 weeks ago. So, while DGB isn't perfect, there's little sense in comparing it to BTC in terms of mining decentralization, they're not even in the same league.

Anything that's still using getwork hasn't been updated in 4-odd years now, so it's had plenty of opportunity to do-so.
