### ISSUE TITLE
New exchange notification

### ISSUE THREAD

**Issue by FreeBitcoins-com** [digibyte/digibyte#202]
Hey fellas,

Sorry to post this here, but I'm not 100% sure where we can get a hold of Jared at... so I'm just throwing a bunch of notes in bottles and letting them loose.

Xploited and I have created an exchange on my FreeBitcoins.com.  We have decided to support Digibyte.  We are strictly crypto2crypto and no stable coins.  Our exchange has no KYC and no withdraw limits.

https://freebitcoins.com/xchange/market/BTC_DGB

We respectfully open our arena for DGB if y'all wish to use it and I humbly appreciate you reading this message!

BAC

**Comment by ChillingSilence** [comment]
Hi BAC, thanks for letting us know. Best to get in touch with the community at large on Telegram, https://t.me/DigiByteCoin
Or tweet @DigiByteCoin on Twitter, and I'm sure they'd love to share that. Thanks!
