### ISSUE TITLE
Biomimicry to improve Digibyte and take it to whole new level! 

### ISSUE THREAD

**Issue by blufrost** [digibyte/digibyte#205]
**Holochain features implemented into Digibyte?**

Digibyte has addressed the issue of scalability by doubling block size, but it seems Holochain has altogether fixed the issue of scalability and how many transactions per second doesn't seem to be an issue, due to the nature of it's decentralization. Holochain also fixes the electrical cost that plagues Bitcoin and other POW projects. 

If Digibyte is forward thinking, then why not consider implementing holochain into the Digibyte core. If we see an improvement in the blockchain space should we not implement it and better Digibyte?

https://www.coinbureau.com/review/holochain-hot/

**Biomimicry**

I think the more we mirror decentralization found in nature, the better the project will be. I remember watching a video a while back on how termites build a structure out of dirt that has a unique design for airflow. A high rise structure was built in Africa that mirrored the termite mound  and in doing so it saved the company a lot of money on electricity and air conditioning cost, because of the way air flowed in the building. Video below.

https://www.youtube.com/watch?v=620omdSZzBs

If we want to improve decentralization and fix the issues that still plague the blockchain space, we should look to nature and see how it operates and learn from it.

**Comment by ChillingSilence** [comment]
At this point there is no intention of any kind of sharding etc on DigiByte, nor is there any concrete discussion about staking. PoW is pretty universally accepted as the most secure, and the most fair way to distribute newly minted DigiByte (or Bitcoin etc), which is where the community wants to stay for the mean time. Alternatively, feel free to make a pull request with some code for staking for review.
