### ISSUE TITLE
Support X11 miners

### ISSUE THREAD

**Issue by PanderMusubi** [digibyte/digibyte#209]
Digibyte can be mined on SHA256 miners or Scrypt miners. Would it be possible to also support X11 miners such as the D3 Antminer?

Implementing this could draw more interest and mining effort for Digibyte for being a multi-algorithm block chain.

Supporting the majority of ASIC miners that are out there will not let them go to waste just yet. This hardware is no longer cost efficient for mining Bitcoin/Litecoin/Dash and this way would prevent then being e-waste already.

**Comment by ChillingSilence** [comment]
At this point DigiByte is more interested in removing some of the ASICs out there in favor of FPGA (Odocrypt), GPU, CPU mining, or an ASIC it could remain a dominant hash power in. The community has overwhelmingly indicated they want to replace an algorithm with ProgPOW, which is where the focus will be. In addition, there's very little reason to replace one ASIC with another.
