### ISSUE TITLE
Wallet freezes when RPC commands executed why wallet is syncing before block 145k

### ISSUE THREAD

**Issue by digibyte** [digibyte/digibyte#21]
After a DigiByte wallet is downloaded the wallet will freeze if a user attempts to run an rpc command such as "getinfo" before the sync has reach blocked 145k. After block 145k the RPC commands work as expected. Block 145k was where the hard fork to multi-algo mining occurred.

A simple if - else statement with block height in the appropriate place should fix this issue.

**Comment by l0rdicon** [comment]
this is fixed here 

https://github.com/digibyte/DigiByteProject/pull/22

simple fix.  The difficulty just needed to use the correct nBits int he calculation. 

It should now not crash when getinfo is ran before block 145000. 

I did test to confirm but a sanity check before merging into master is always good :)

**Comment by digibyte** [comment]
Fixed with https://github.com/digibyte/DigiByteProject/commit/a68572624d8a1b80e337194fa3dc7922f66ffde9
