### ISSUE TITLE
Add Unstoppable Domain Addresses

### ISSUE THREAD

**Issue by trymeouteh** [digibyte/digibyte#210]
Please add support for using unstoppable domains names as cryptocurrency addresses you can enter in to send payments to within the desktop and mobile wallet. Unstoppable domains allow you to send crypto to .zil and .crypto domain names.

**Comment by ChillingSilence** [comment]
The DigiByte Core and mobile wallets intentionally desire to remain neutral and not favor any independent 3rd-party.

If users want to use .zil or .crypto then there are dozens of alternative wallets available for DIgiByte and several of them support those.
