### ISSUE TITLE
node

### ISSUE THREAD

**Issue by moneybag** [digibyte/digibyte#214]
How can I run a btcmynode together with digibyte-node together on a raspi 4 4gb?

**Comment by ChillingSilence** [comment]
There's likely not enough RAM on a Pi4 4GB.
If there is, simply downloading the aarch64 package and running that is the fastest way to do this. There are no special requirements otherwise to run multiple daemons on the same system.

**Comment by moneybag** [comment]
> There's likely not enough RAM on a Pi4 4GB.
> If there is, simply downloading the aarch64 package and running that is the fastest way to do this. There are no special requirements otherwise to run multiple daemons on the same system.

i got this error  aarch64

root@myNode:/home/admin# bash: /bin/digibyted: cannot execute binary file: Exec format error

**Comment by ChillingSilence** [comment]
You need a 64-bit OS. Raspbian is not by default.

**Comment by moneybag** [comment]
ok

**Comment by SmartArray** [comment]
https://medium.com/@YoshiJaeger/running-digibyte-core-on-a-raspberry-pi-3-4-a7350dabbde0?utm_source=share&utm_medium=ios_app
