### ISSUE TITLE
sendtoaddress transaction not being broadcast on regtest network

### ISSUE THREAD

**Issue by buck54321** [digibyte/digibyte#217]
When sending transactions using `sendtoaddress` on the regtest network, the transaction doesn't appear to be broadcast. 

**Steps to reproduce:**

Starting with a fresh `-regtest` node.

1. `digibyte-cli -regtest -rpcwallet= generate 110` 
2. `digibyte-cli -regtest createwallet secondwallet`
3. ``digibyte-cli -regtest -rpcwallet= sendtoaddress `digibyte-cli -regtest -rpcwallet=secondwallet getnewaddress` 10``

Now, doing `digibyte-cli -regtest getrawmempool` shows nothing in mempool.

`digibyte-cli -regtest -rpcwallet=secondwallet getwalletinfo` shows that the wallet has registered the transaction, but shows as unconfirmed.

```
{
  "walletname": "secondwallet",
  "balance": 0.00000000,
  "unconfirmed_balance": 10.00000000,
  "immature_balance": 0.00000000,
  ...
}
```

`digibyte-cli -regtest -rpcwallet=secondwallet listunspent 0` shows the output. 

Using `-txindex` and running `getrawtransaction` fails to find it.

It is not included in any subsequently mined blocks.

Further, if I run a second node and connect the two, the second node never appears to receive the transaction. 

On Linux Mint 18.3

**Comment by SmartArray** [comment]
I ran into the same issue. At the very first glance, it looks like a bug. **Indeed, it's a feature.**

You will be able to see the expected mempool transactions as soon as you disable the _dandelion anonymization protocol_.
You can do this by specifying `disabledandelion=1` in your `digibyte.conf`.
