### ISSUE TITLE
Wallet try to spent send not matured inputs

### ISSUE THREAD

**Issue by Niceman35** [digibyte/digibyte#25]
Looks like where is a bug somethere and transactions are stuck in my pools.
Wallet send transactions with not matured coins. 
Here is example:
# listtransactions:

```
{
    "account" : "",
    "address" : "DDntRH8Tkf3TNC1TzcMETVJSmWTwCjJCxh",
    "category" : "immature",
    "amount" : 7309.79908817,
    "confirmations" : 69,
    "generated" : true,
    "blockhash" : "a0da7d394fcf24f2921d3c8968f219f3872c1b484a76fad8e2df4e0ba23b78c5",
    "blockindex" : 0,
    "blocktime" : 1413207303,
    "txid" : "022866c8079ce8ac7f9ea95058ed25f7a0204396f493d7d91d5f92ef11c69ed0",
    "walletconflicts" : [
    ],
    "time" : 1413207303,
    "timereceived" : 1413207434
},
    "account" : "",
    "address" : "DDntRH8Tkf3TNC1TzcMETVJSmWTwCjJCxh",
    "category" : "immature",
    "amount" : 7309.79908817,
    "confirmations" : 60,
    "generated" : true,
    "blockhash" : "073b35379c927fffd3951635e5ed692de32f8ddda1d66089aecbf86ed0a42bd5",
    "blockindex" : 0,
    "blocktime" : 1413207399,
    "txid" : "6b0c43f67ecd84beb0a744b84f6e7c3d4916e9e02bfe2a5d3980eb1bf7135f21",
    "walletconflicts" : [
    ],
    "time" : 1413207399,
    "timereceived" : 1413207434
},
```
# 
# Here is a 'listunspent'  :

```
{
    "txid" : "022866c8079ce8ac7f9ea95058ed25f7a0204396f493d7d91d5f92ef11c69ed0",
    "vout" : 0,
    "address" : "DDntRH8Tkf3TNC1TzcMETVJSmWTwCjJCxh",
    "account" : "",
    "scriptPubKey" : "76a9145ee6b1fd3e7d5debc048e0fc828c4ddb4dd8955388ac",
    "amount" : 7309.79908817,
    "confirmations" : 76
},
{
    "txid" : "6b0c43f67ecd84beb0a744b84f6e7c3d4916e9e02bfe2a5d3980eb1bf7135f21",
    "vout" : 0,
    "address" : "DDntRH8Tkf3TNC1TzcMETVJSmWTwCjJCxh",
    "account" : "",
    "scriptPubKey" : "76a9145ee6b1fd3e7d5debc048e0fc828c4ddb4dd8955388ac",
    "amount" : 7309.79908817,
    "confirmations" : 67
},
```
# 

This not matured transactions already shown as unspent inputs.

Trying to make transaction and get error but error transaction is created in the wallet.
# listtransactions : 

```
{
    "account" : "",
    "address" : "DJjrkQQHjrgv8srXDtQ5i7rDCHvbRztTjN",
    "category" : "send",
    "amount" : -1419.36075819,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
},
{
    "account" : "",
    "address" : "DMV3EzNamZzwF6ZvcrbDdMTgP66cWhUguR",
    "category" : "send",
    "amount" : -1502.97468120,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
},
{
    "account" : "",
    "address" : "DQnomP6VGJEQwvjPdrSQg2217C194R83cc",
    "category" : "send",
    "amount" : -10962.45096151,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
},
{
    "account" : "",
    "address" : "DDWuzcQFtohhsJLgGoZPg3g9rzy9cJrZpy",
    "category" : "send",
    "amount" : -1171.72745829,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
},
{
    "account" : "",
    "address" : "DFhd8UdMCgDzAYEts9kp53CyjSDhyGxiEc",
    "category" : "send",
    "amount" : -369.99779667,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
},
{
    "account" : "",
    "address" : "DCkzxCq83tUCueMPVEg4DkcUkqQHSkdbcX",
    "category" : "send",
    "amount" : -816.45970211,
    "fee" : 0.00000000,
    "confirmations" : -1,
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "walletconflicts" : [
    ],
    "time" : 1413208406,
    "timereceived" : 1413208406
}
```
# 
# if we decode transaction 7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc we get:

 {
    "txid" : "7b82557b8d1d99b04ff8bbba6267f6a7a15800677771a48e4af707182d70a1bc",
    "version" : 1,
    "locktime" : 0,
    "vin" : [
        {
            "txid" : "022866c8079ce8ac7f9ea95058ed25f7a0204396f493d7d91d5f92ef11c69ed0",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "30440220030eb9e59b8f26ac2a8dff4e5a04c6f0fb05694a11accfe99e8ed5abc1fc254e02202d259b7b7d99f65fe79e3cbf0819fc8e1aca57570fd6950d3065d269b14fcc5501 03568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19",
                "hex" : "4730440220030eb9e59b8f26ac2a8dff4e5a04c6f0fb05694a11accfe99e8ed5abc1fc254e02202d259b7b7d99f65fe79e3cbf0819fc8e1aca57570fd6950d3065d269b14fcc55012103568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19"
            },
            "sequence" : 4294967295
        },
        {
            "txid" : "6b0c43f67ecd84beb0a744b84f6e7c3d4916e9e02bfe2a5d3980eb1bf7135f21",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "3045022100e830277c33247c420770b67773982fe8f061d644ee9e51fb719be4e38ebce1cd02206262f200c5550c8c5135579ef91bcf8bbfb9412e3df1f3801766b2ef523dd24f01 03568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19",
                "hex" : "483045022100e830277c33247c420770b67773982fe8f061d644ee9e51fb719be4e38ebce1cd02206262f200c5550c8c5135579ef91bcf8bbfb9412e3df1f3801766b2ef523dd24f012103568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19"
            },
            "sequence" : 4294967295
        },
        {
            "txid" : "29b3800e25e0413acffbf9205783a2b0fcc4f85143a633dc40d6d48b0c264015",
            "vout" : 0,
            "scriptSig" : {
                "asm" : "3045022100d0e2a30ee26d443d272f5caad6cc9283a560467b7717dbd3c5019992510fc92102207919ec4cdae191b6ecddbbefef72fece0cc35ce9df679900911c3b450b05bf7301 03568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19",
                "hex" : "483045022100d0e2a30ee26d443d272f5caad6cc9283a560467b7717dbd3c5019992510fc92102207919ec4cdae191b6ecddbbefef72fece0cc35ce9df679900911c3b450b05bf73012103568926b8c7e34cac0376faed263e4f44273d6a97258ee50a356a42ef5285ce19"
            },
            "sequence" : 4294967295
        }
    ],
    "vout" : [
        {
            "value" : 816.45970211,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 539330f2ff350e70b7594c31832cb63540e035d1 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914539330f2ff350e70b7594c31832cb63540e035d188ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DCkzxCq83tUCueMPVEg4DkcUkqQHSkdbcX"
                ]
            }
        },
        {
            "value" : 369.99779667,
            "n" : 1,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 73d81a9569de8003de770f16aa5729c7a23649bd OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a91473d81a9569de8003de770f16aa5729c7a23649bd88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DFhd8UdMCgDzAYEts9kp53CyjSDhyGxiEc"
                ]
            }
        },
        {
            "value" : 1171.72745829,
            "n" : 2,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 5be15ab8081df8e02fcf38515ea1c3f07022e558 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a9145be15ab8081df8e02fcf38515ea1c3f07022e55888ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DDWuzcQFtohhsJLgGoZPg3g9rzy9cJrZpy"
                ]
            }
        },
        {
            "value" : 10962.45096151,
            "n" : 3,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 d78c31c62d3fb4ec6e5e6f2d6409265a360bdace OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914d78c31c62d3fb4ec6e5e6f2d6409265a360bdace88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DQnomP6VGJEQwvjPdrSQg2217C194R83cc"
                ]
            }
        },
        {
            "value" : 1502.97468120,
            "n" : 4,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 b3479437441552635378ab40711d8e6771104ee8 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914b3479437441552635378ab40711d8e6771104ee888ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DMV3EzNamZzwF6ZvcrbDdMTgP66cWhUguR"
                ]
            }
        },
        {
            "value" : 5686.42590654,
            "n" : 5,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 55d03cc27b4cafa29ef22f835057d462e7dc950f OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a91455d03cc27b4cafa29ef22f835057d462e7dc950f88ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DCxqS9YvW6YzbbEqnVxtzmvBpeCHx9zBhY"
                ]
            }
        },
        {
            "value" : 1419.36075819,
            "n" : 6,
            "scriptPubKey" : {
                "asm" : "OP_DUP OP_HASH160 952cae9ab209da69e49569438f6408bc2d6912c0 OP_EQUALVERIFY OP_CHECKSIG",
                "hex" : "76a914952cae9ab209da69e49569438f6408bc2d6912c088ac",
                "reqSigs" : 1,
                "type" : "pubkeyhash",
                "addresses" : [
                    "DJjrkQQHjrgv8srXDtQ5i7rDCHvbRztTjN"
                ]
            }
        }
    ]
 }
# 
# As you can see, this transactions have inputs:

 {
29b3800e25e0413acffbf9205783a2b0fcc4f85143a633dc40d6d48b0c264015
6b0c43f67ecd84beb0a744b84f6e7c3d4916e9e02bfe2a5d3980eb1bf7135f21
#  }

which is not matured as shown above.

Looks like you forget to add new mature value in some function. Unfortunately I can't find it by myself and don't have much time for this, but with this bug I can't payout pool reward to my users.

PS: after this error transaction, unspent inputs is not changed and next transaction get "walletconflicts" already.

If you will fix it, please write to coinminepw@gmail.com with info about new commit.

With best regards,
Victor

**Comment by l0rdicon** [comment]
Hey Victor,

I believe this problem is fixed in our development branch but hasn't been
pushed to master yet. There were 2 checks that weren't passing in the
proper values. These have been updated in the dev branch.

There's nothing in the dev branch that would create a problem so you can
compile from the dev branch if you would like to test.

A real world test would be much appreciated in fact.

I'm 95% sure your issues were being caused by this but if your still having
them further investigation will be required

Scott

**Comment by digibyte** [comment]
v3.0.2 has been merged to master. Issue should be fixed. Please update. Thanks!
