### ISSUE TITLE
Transaction amount too small.

### ISSUE THREAD

**Issue by flound1129** [digibyte/digibyte#41]
getting this now for amounts less than around 0.5 DGB using sendmany.

{'message': u'Transaction amount too small', 'code': -6, 'error': {u'message': u'Transaction amount too small', u'code': -6}}

**Comment by digibyte** [comment]
Hello,

With the digispeed hard fork the minimum TX was set to 1 DGB in an effort to prevent bloat attacks on the network. If you have anymore questions let us know.

Cheers,
