### ISSUE TITLE
MacOS .dmg fails to mount

### ISSUE THREAD

**Issue by ghost** [digibyte/digibyte#59]
The MacOS .dmg is not mounting, hangs in Finder while "Attaching" and eventually times out.

**Comment by digibyte** [comment]
Which wallet version? Also what version of OSX are you running?

**Comment by ghost** [comment]
Digibyte 6.14.1
MacOS 10.11.6

**Comment by digibyte** [comment]
Make sure you are on v6.14.2. That should fix your issue.
