### ISSUE TITLE
Gitian Building

### ISSUE THREAD

**Issue by ShawnKimble** [digibyte/digibyte#61]
Is this project supporting the Gitian Building process for binaries, and if so, where are those signatures in the project stored?

**Comment by yarblar** [comment]
This is a little diff build I must admit but worked for me. 
not sure why this page included all this setup etc anyhow 
Gitian building https://github.com/digibyte/digibyte/blob/master/doc/gitian-building.md
 the sigs are at the bottom of this page  
However if you look at the build for you system in the docs section and you can control all the depends as you wish.  I just let it fetch the ones I wanted and it cleaned up as well quit slick.
If you want to control everything check out :
https://github.com/digibyte/digibyte/blob/master/depends/description.md
https://github.com/digibyte/digibyte/blob/master/depends/packages.md
