### ISSUE TITLE
Error After Wallet Upgrade - Work Queue Depth Exceeded

### ISSUE THREAD

**Issue by daygle** [digibyte/digibyte#62]
Hi guys,

Just to let you know that the recent wallet upgrade is now trowing the below error. 

I have compiled Digibyte on a Debian 8 server with integration with NOMP - NOMP reports the below error which comes from the wallet.

###
Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"]}],"id":1493034425617}
Reponse Data: Work queue depth exceeded

**Comment by digibyte** [comment]
This an issue with NOMP. Make sure your version of stratum supports SegWit blocks and getblocktemplate.
