### ISSUE TITLE
Play and claim doesnt seem to work

### ISSUE THREAD

**Issue by FrankiusT** [digibyte/digibyte#65]
Followed instructions perfectly, everything linked correctly but it doesnt register that I have played nor does it pay out.

This issue tracker is only for technical issues related to digibyte-core.

General digibyte questions and/or support requests and are best directed to the [DigiByte StackExchange](https://digibyte.stackexchange.com).

For reporting security issues, please read instructions at [https://digibytecore.org/en/contact/](https://digibytecore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of digibyte-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by G1ne** [comment]
Yes I am currently having the same problems with DGB Gaming.

**Comment by digibyte** [comment]
This repository is for the DigiByte core protocol and wallet, not DigiByte Gaming.
