### ISSUE TITLE
Runtime C++ error near end of wallet sync...2 weeks remaining!!!

### ISSUE THREAD

**Issue by G1ne** [digibyte/digibyte#68]
This issue tracker is only for technical issues related to digibyte-core.

General digibyte questions and/or support requests and are best directed to the [DigiByte StackExchange](https://digibyte.stackexchange.com).

For reporting security issues, please read instructions at [https://digibytecore.org/en/contact/](https://digibytecore.org/en/contact/).

### Describe the issue

Wallet will not sync

#### If so, please list the steps to reproduce below:
1. Open wallet as admin
2. Wait
3. Issue appears
[DIGILOG.txt](https://github.com/digibyte/digibyte/files/1022129/DIGILOG.txt)

### Expected behaviour
Wallet sync

### Actual behaviour
Wallet Crashes...C++ runtime dialouge box.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of digibyte-core are you using?
6.14.2

### Machine specs:
- OS: Wn 7
- CPU: 3.00ghz
- RAM: 3gb
- Disk size: 80gb
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by SirMcChadders** [comment]
I am having this same issue. Its now been 4 days and it just keeps crashing.

**Comment by AdaelRuiz** [comment]
i am have this problem

**Comment by G1ne** [comment]
Hi,

Sorry I should have came back here, but been busy.

I managed to sort the problem.

1. Save any wallets you have (Backup).

2. Remove application.

3.  Restart Computer.

4.  Make sure you have enough space on HDD for min requirements!!!

5. Close all other apps/programs and re-install.

Let me know if this works for you.

If you can get a log for the error BEFORE you do this.  Post it here and I will see if it may be another problem.

The process above should resolve most errors like this.

I have spoken to Jared and confirmed that these steps have worked.

Good luck!!

**Comment by AdaelRuiz** [comment]
Thank you very much for the support I am also doing everything
possible to achieve the installation of the wallet and I am removing
and running again thanks beforehand


2017-07-07 16:21 GMT-05:00 G1ne <notifications@github.com>:

**Comment by G1ne** [comment]
No problems.  Let me know.

**Comment by AdaelRuiz** [comment]
Hola.

Acabo de firmar la petición "Instituto Mexicano del Seguro Social: Que el
IMSS (Centro Medico Siglo XXI) refiera a Gigi al Hospital ST. Jude
Children´s" y pensé que te podría interesar.

Estamos intentando conseguir 73.029 firmas y necesitamos todo el apoyo que
podamos conseguir. Puedes leer más y firmar la petición aquí:

http://chng.it/VndNFKgBnF

¡Gracias!
Ruben Antonio
