### ISSUE TITLE
Still got error while build on linux

### ISSUE THREAD

**Issue by ghost** [digibyte/digibyte#7]
I still get following error if I try to build it on ubuntu 12.04

util.h:102:2: error: #error missing boost sleep implementation
make: **\* [obj/checkpoints.o] Error 1

**Comment by l0rdicon** [comment]
I just built on a fresh ubuntu 12.04 install with no issues. You are likely missing dependencys as they've changed some from the previous client. 

Follow the instructions at 

https://github.com/digibyte/DigiByteProject/blob/master/doc/build-unix.md 

I'll leave this open for a while. Message back if you need any more guidance.

**Comment by ghost** [comment]
All the dependencies are installed. Still got this error. I installed a lot of other coin deamons and never get this error before. Looks like there is still something special in your code

**Comment by l0rdicon** [comment]
There's nothing special in our code that could cause this. 

Following the instructions I've managed to compile it on ubuntu 12.04 on 6 different installs ranging from 6 month old desktop builds with an array of dependency issues I had to work through to a fresh vm instance and I've been unable to reproduce your error. 

The gitian system which the binarys are built from use ubuntu 12.04.

The only thing I can suggest is that you make sure the code your working from is up to date. 

git pull                  in the directory.   

Or delete the repo altogether and clone it again. Other then that there is a problem with your linux environment and its not finding boost.   You can post your configure log and I will be glad to check it over.

**Comment by ghost** [comment]
That is very strang. I made a new git clone, didn't work again. So I tried it on a clean installed ubuntu server12.04 x64 like you said it should work. But it didn't work too. I tried to build dogecoin, litecoin and auroracoin too and all this worked with any error. So it really looks like there is a problem in the code.

**Comment by l0rdicon** [comment]
I've been building on Ubuntu desktop, I have not tried on the server
release which is why I likely have been unable to reproduce the error.

I suspect the version of boost is an older 'stable' release for the apt
repos on the server edition.

Our code is almost absolutely identical to the bitcoin master repo (0.9.1)
so you should have the same issue compiling the current bitcoin master if
you were to try.

I will install a server Ubuntu build this evening and confirm my
suspecision

**Comment by ghost** [comment]
We have currently running following version of BTC wallet: version: "99900"

**Comment by l0rdicon** [comment]
So, I just compiled it from on a fresh ubuntu server 12.04 x64 downloaded directly from ubuntu.com in a vm instance, following the document at https://github.com/digibyte/DigiByteProject/blob/master/doc/build-unix.md exactly with no other steps required (other then installing the requirement for add-apt-repository) and I am still unable to reproduce this error. It compiled for me with no issue. 

I need your config.log to investigate further. It can be found in the base directory.

**Comment by ghost** [comment]
I tried a fresh install again. This time with ./autogen.sh ./configure ...
now I recieve following error:
/usr/bin/ld: ../src/leveldb/libleveldb.a(db_impl.o): relocation R_X86_64_32S against `vtable for leveldb::DB' can not be used when making a shared object; recompile with -fPIC
../src/leveldb/libleveldb.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[3]: **\* [digibyted] Error 1

The times before I built it with make -f makefile.unix

**Comment by ghost** [comment]
After a 3rd complete clean install it works now. Thanks god. ;)
