### ISSUE TITLE
Looking for a proper correct digibyte.conf file, please

### ISSUE THREAD

**Issue by imrecsoka** [digibyte/digibyte#70]
HI,

I am looking for the official or proper correct digibyte.conf file, please

Thanks

**Comment by TheComputerGenie** [comment]
```
server=1
rpcuser=MyUser
rpcpassword=MyPass
rpcallowip=127.0.0.0/24
rpcallowip=192.168.1.0/24
daemon=1
gen=0
txindex=1
```
If using it on a custom port, then you also need to add like:
port=12124
rpcport=14122
If using it for mining, then you also need to add like:
algo=sha256d

**Comment by imrecsoka** [comment]
You can try to teamviewer with me and see what I am doing? i have really tried so much i can not get it to work... maybe im  missing something small... ?

**Comment by yarblar** [comment]
The config file is fine start with https://github.com/digibyte/digibyte/blob/master/doc/README.md and then go into the build link on this file for the system you are compiling for.  I just build it for win 10 using his exact directions under win10-linux beta as he suggested. The only place I got tripped up was at CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
So change $PWD to the actual path.  I am no expert at this but I hope this helps you.
