### ISSUE TITLE
Feature Request: Multi-algo GBT

### ISSUE THREAD

**Issue by flound1129** [digibyte/digibyte#75]
As a pool operator, it would be nice if I didn't need to run a copy of DGB per algo.

Being able to select the algorithm when calling getblocktemplate would be optimal.

**Comment by digibyte** [comment]
Thank you for the suggestion! This is a great idea. We will look into it for a future release.

**Comment by ChillingSilence** [comment]
This is an enhancement we are looking at for 6.17.1

**Comment by ChillingSilence** [comment]
This has now been included in 6.17.2
