### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by sanderploegsma** [digibyte/digibyte#76]
### Describe the issue
Digibyte Core crashes during/after syncing when starting. 

#### If so, please list the steps to reproduce below:
1. Start the app
2. Crashes during startup

### Screenshots.
<img width="592" alt="screen shot 2017-06-05 at 21 04 31" src="https://cloud.githubusercontent.com/assets/1564254/26798956/ee1d8b4e-4a32-11e7-8600-c6e7f857c805.png">
<img width="662" alt="screen shot 2017-06-05 at 21 05 49" src="https://cloud.githubusercontent.com/assets/1564254/26798961/f245f7f6-4a32-11e7-868a-df65510b5a7e.png">

### What version of digibyte-core are you using?
See screenshot

### Machine specs:
- OS: macOS 10.12.5
- CPU: Intel core i5 (3.1GHz)
- RAM: 16 GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Debug log: https://pastebin.com/raw/GQHsHADi

**Comment by G1ne** [comment]
This may help.

Try issue #68 https://github.com/digibyte/digibyte/issues/68

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
