### ISSUE TITLE
old wallet download linke please? version 6 is broken for solo mining.

### ISSUE THREAD

**Issue by imrecsoka** [digibyte/digibyte#79]
This issue tracker is only for technical issues related to digibyte-core.

General digibyte questions and/or support requests and are best directed to the [DigiByte StackExchange](https://digibyte.stackexchange.com).

For reporting security issues, please read instructions at [https://digibytecore.org/en/contact/](https://digibytecore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of digibyte-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by digibyte** [comment]
Please see: https://github.com/digibyte/digibyte/issues/80
