### ISSUE TITLE
test_digibyte / base58 test failures on test_digibyte linux binary

### ISSUE THREAD

**Issue by mangelajo** [digibyte/digibyte#86]
### Describe the issue

Test case failure on precompiled x64 binary for linux

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. run bin/test_digibyte

### Expected behaviour
Tests passing

### Actual behaviour

test/base58_tests.cpp(165): error: in "base58_tests/base58_keys_valid_parse": !IsValid:["1AGNa15ZQXAZUgFiqJ2i7Z2DPU2J6hW62i","65a16059864a2fdbc7c99a4723a8395bc6f188eb",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(168): error: in "base58_tests/base58_keys_valid_parse": addrType mismatch["1AGNa15ZQXAZUgFiqJ2i7Z2DPU2J6hW62i","65a16059864a2fdbc7c99a4723a8395bc6f188eb",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(165): error: in "base58_tests/base58_keys_valid_parse": !IsValid:["1Ax4gZtb7gAit2TivwejZHYtNNLT18PUXJ","6d23156cbbdcc82a5a47eee4c2c7c583c18b6bf4",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(168): error: in "base58_tests/base58_keys_valid_parse": addrType mismatch["1Ax4gZtb7gAit2TivwejZHYtNNLT18PUXJ","6d23156cbbdcc82a5a47eee4c2c7c583c18b6bf4",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(165): error: in "base58_tests/base58_keys_valid_parse": !IsValid:["1C5bSj1iEGUgSTbziymG7Cn18ENQuT36vv","7987ccaa53d02c8873487ef919677cd3db7a6912",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(168): error: in "base58_tests/base58_keys_valid_parse": addrType mismatch["1C5bSj1iEGUgSTbziymG7Cn18ENQuT36vv","7987ccaa53d02c8873487ef919677cd3db7a6912",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(165): error: in "base58_tests/base58_keys_valid_parse": !IsValid:["1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu","adc1cc2081a27206fae25792f28bbc55b831549d",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(168): error: in "base58_tests/base58_keys_valid_parse": addrType mismatch["1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu","adc1cc2081a27206fae25792f28bbc55b831549d",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
test/base58_tests.cpp(165): error: in "base58_tests/base58_keys_valid_parse": !IsValid:["1JwMWBVLtiqtscbaRHai4pqHokhFCbtoB4","c4c1b72491ede1eedaca00618407ee0b772cad0d",{"addrType":"pubkey","isPrivkey":false,"isTestnet":false}]
### What version of digibyte-core are you using?

digibyte-6.14.2-x86_64-linux-gnu.tar.gz

List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: centos 7.4
- CPU: x64
- RAM: 2GB
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
https://paste.fedoraproject.org/paste/~MAfB8~IMgc1y2B59QCp1g

**Comment by bnleach** [comment]
Was this solved? I am having the same issue.

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
