### ISSUE TITLE
test_digibyte / key_tests/key_test1 fails

### ISSUE THREAD

**Issue by mangelajo** [digibyte/digibyte#89]
### Describe the issue

Test case failure on precompiled x64 binary for linux, 

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. run bin/test_digibyte

### Expected behaviour
Tests passing

### Actual behaviour

test/key_tests.cpp(105): error: in "key_tests/key_test1": check addr1.Get() == CTxDestination(pubkey1.GetID()) has failed
test/key_tests.cpp(106): error: in "key_tests/key_test1": check addr2.Get() == CTxDestination(pubkey2.GetID()) has failed
test/key_tests.cpp(107): error: in "key_tests/key_test1": check addr1C.Get() == CTxDestination(pubkey1C.GetID()) has failed
test/key_tests.cpp(108): error: in "key_tests/key_test1": check addr2C.Get() == CTxDestination(pubkey2C.GetID()) has failed

### What version of digibyte-core are you using?

digibyte-6.14.2-x86_64-linux-gnu.tar.gz

List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: centos 7.4
- CPU: x64
- RAM: 2GB
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
https://paste.fedoraproject.org/paste/~MAfB8~IMgc1y2B59QCp1g

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
