### ISSUE TITLE
test_digibyte / main_tests/subsidy_limit_test fails

### ISSUE THREAD

**Issue by mangelajo** [digibyte/digibyte#91]
### Describe the issue

Test case failure on precompiled x64 binary for linux, 

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. run bin/test_digibyte

### Expected behaviour
Tests passing

### Actual behaviour

test/main_tests.cpp(53): error: in "main_tests/subsidy_limit_test": check nSubsidy <= 50 * COIN has failed
test/main_tests.cpp(53): error: in "main_tests/subsidy_limit_test": check nSubsidy <= 50 * COIN has failed
### What version of digibyte-core are you using?

digibyte-6.14.2-x86_64-linux-gnu.tar.gz

List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: centos 7.4
- CPU: x64
- RAM: 2GB
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
https://paste.fedoraproject.org/paste/~MAfB8~IMgc1y2B59QCp1g

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
