### ISSUE TITLE
Colors / text in 6.15.1

### ISSUE THREAD

**Issue by ChillingSilence** [digibyte/digibyte#96]
#### If so, please list the steps to reproduce below:
1. Compile 6.15.1 for Windows (32-bit or 64-bit)
2. Set text size to 150% (And possibly have a 4K monitor)
3. Run DigiByte Core

### Expected behaviour
Text should not overlap. Text should be visible in the Options menu

### Actual behaviour
Text in Recent Transactions is overlapped. Settings --> Options text is mostly invisible

### Screenshots.
<img width="502" alt="digibyte-6 15 1-compiled" src="https://user-images.githubusercontent.com/162461/34068877-db555474-e2a8-11e7-9d39-fe7856cda790.png">

### What version of digibyte-core are you using?
Built 20171216 from Git, DigiByte Core version v6.15.1.0-g8ab7d8b9e (64-bit)

### Machine specs:
- OS: Windows 10 64-bit
- CPU: i7 7700k
- RAM: 32GB
- Disk size: 18TB
- Disk Type (HD/SDD): Both

### Any extra information that might be useful in the debugging process.
See attached screenshot. Increasing window width by approx 15% is sufficient to avoid them overlapping when sending / receiving 4 digits before the decimal point

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
