### ISSUE TITLE
Useless / harmful code in difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [digibyte/digibyte#98]
The difficulty algorithm includes useless and potentially harmful code that has spread to many coins. It would be good if it could be removed from all coins using it.  I'm referring to the code at the bottom of this post and it's v3 and v4 brothers.  

A per block limit on the difficulty adjustment might be acceptable (although it's better to just increase the window of the averaging period), but this code has the opposite of the desired effect.  For example, if there has been a recent increase in hashrate, then difficulty starts rising for a few blocks, sometimes even faster per block than the limits if the difficulty was already too high (solvetime average was above Target). This is good to the extent no limits are best (my position), but it is contrary to the implied function of the limits.  The main problem occurs if there is a real, sustained hashrate increase (or decrease).  After a few blocks of rising quickly as desired, the rise per block is suddenly severely limited to about 0.5% per block, then slowly increases to about 1.5% per block (with 16% nMaxAdjustUp) until it reaches the necessary difficulty. The problem can be seen clearly in probably every coin using this code during startup: it's not allowed to rise fast enough and takes about 500 blocks to reach the correct difficulty.  HUSH took 1000 blocks (16% rise limit). After startup, the Digibyte and Zcash algorithms are slow enough in responding to hash rate changes that the harmful effects of the code are not normally seen because the limits are not reached. As long as the limits are never reached in a coin, it does not cause harm.  It normally causes harm when the limits are reached, which can be seen as semi-straight line curving up or down rather than having the normal noisy fluctuations.

Other than startup, the problem is how it can affect unsuspecting victims such as BTG who followed my recommendation to have a faster responding algorithm than the Zcash code they copied (they need to respond faster because their Target is much slower, 600 seconds instead of 150 seconds).  Under the belief that the limits were a per-block limit, I did not remove them.  Even worse, by not being symmetrical limits, they are causing the same problem that was seen in BCH's original EDA: blocks being issued too fast on average and encouraging "hash attacks".  Faster allowed limits on fall than rise cause blocks to be issued too quickly, if the limits are reached often, and vice versa.  But limits should not be used because the data is real data that should not be ignored, and restrictive symmetrical limits end up being the same as a longer averaging window.  

So when coins with a longer Target seek a good algorithm, good testing will reveal that the overall Digishield algorithm falls apart if they try to make it respond faster with a smaller window, but they will probably not realize it is because of the bad code below.  

Another problem is that using MTP does more harm than good, always giving 5 or 6 block away at low difficulty before beginning to respond, potentially cause persistent predictable but small oscillations.

I covered these 3 problems (useless / harmful limits, asymmetry, and MTP) in more detail [here with charts on live coins](https://github.com/zawy12/difficulty-algorithms/issues/7).

```
consensus.nMaxAdjustDown = 40; // 40% adjustment down
        consensus.nMaxAdjustUp = 20; // 20% adjustment up
```

```
        consensus.nMinActualTimespan = consensus.nAveragingTargetTimespan * (100 - consensus.nMaxAdjustUp) / 100;
        consensus.nMaxActualTimespan = consensus.nAveragingTargetTimespan * (100 + consensus.nMaxAdjustDown) / 100;
```

```	
if (nActualTimespan < params.nMinActualTimespan)
		nActualTimespan = params.nMinActualTimespan;
	if (nActualTimespan > params.nMaxActualTimespan)
		nActualTimespan = params.nMaxActualTimespan;
```

**Comment by salmanmarvasti** [comment]
has anyone looked at this

**Comment by zawy12** [comment]
Bitcoin has the same kind of code with much larger limits, 1/4 and 4x.  It works as expected there because Bitcoin does not use a rolling average.  Their previous 2016 blocks have a constant D that was perfectly correct for the average of the previous 2016 blocks.   But in a rolling average, the D changes every block, so is only correct for the previous block.  But this limit is applied to the previous N blocks.  Bitcoin limits an  (N*D)*T/(N\*avgST) where ST=solvetime.  By limiting only the range of N\*ST it limit the whole thing. 
 Since the numerator is a constant, it only needs to limit the denominator.  Rolling avg coins using this code are limiting D\*T/ (N\*avgST).  The numerator and denominator are disconnected in a way that does not happen in bitcoin.  The goal should be to limit D\*T/ST.

**Comment by jdabs** [comment]
How does this apply to DGB? You seem to suggest that this is a non-issue until someone forks the repo for their own uses?

**Comment by zawy12** [comment]
It does not apply to DGB if the community does not care about maintaining useless code that can harm others if they try to improve it.  In that case, the title of this issue could be changed to "DGB community is a bit too sloppy in coding and a little bit amoral."

**Comment by zawy12** [comment]
BTW, if there ever is a hard fork, about 30 lines of Digishield difficulty coding could be replaced with the following difficulty algorithm to have a smoother difficulty and 1/2 as many delays.
```
ST = timestamp[-1]-timestamp[-2]
ST = min(T*(6+1),max(ST, -(6-1)*T)
next_target = prev_target*(50+ST/T-1)/50
```
Simulations:
![image](https://user-images.githubusercontent.com/18004719/34959323-fcc10b86-fa03-11e7-9886-8c45fde3ed32.png)

![image](https://user-images.githubusercontent.com/18004719/34959346-1ebbc3fc-fa04-11e7-83fa-94a3c2081bb5.png)

**Comment by digibyte** [comment]
While we are flattered some of our code ended up in BTG and BCH the various pieces are needed for initial blockchain downloads for DigiByte clients. DGB has evolved over the past 5 years through multiple hard forks and this is a reflection of that.
