### ISSUE TITLE
configure/make issue with Digibyte 

### ISSUE THREAD

**Issue by bnleach** [digibyte/digibyte#99]
I am installing digibyte on Ubuntu 14.04. After running the steps listed below I had the tests failed 9log attached) please let me know how to correct this issue.
./autogen.sh
./configure --enable-wallet --with-gui --with-miniupnpc
make check

after the check it returned 2 failed tests (see attached ) my machine specs are below
OS: windows 7 ultimate
4810mq processor
AMD 41709 firepro-2GB
INTEL HD graphics
16 GB RAM
1TB HDD

the Ubuntu is running on VMWARE 14
[test-suite.log](https://github.com/digibyte/digibyte/files/1597099/test-suite.log)
[test-suite.log](https://github.com/digibyte/digibyte/files/1597100/test-suite.log)
[test-suite.log](https://github.com/digibyte/digibyte/files/1597103/test-suite.log)
[test-suite.log](https://github.com/digibyte/digibyte/files/1597104/test-suite.log)

**Comment by digibyte** [comment]
Please try the latest release: https://github.com/digibyte/digibyte/releases/tag/v.6.16.1
